# Rede
networks:
  korp-network:
    driver: bridge


services:
# Container 1
  http-server-projeto-korp:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: http-server-projeto-korp
    networks:
      - korp-network

# Container 2
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/http-server-projeto-korp.conf:/etc/nginx/conf.d/default.conf
    networks:
      - korp-network
    depends_on:
      - http-server-projeto-korp